# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{brightcove-api}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Czarnecki"]
  s.date = %q{2010-07-29}
  s.description = %q{Ruby gem for interacting with the Brightcove media API. http://docs.brightcove.com/en/media/}
  s.email = %q{dczarnecki@agoragames.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/brightcove-api.rb",
     "test/helper.rb",
     "test/test_brightcove-api.rb"
  ]
  s.homepage = %q{http://github.com/agoragames/brightcove}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby gem for interacting with the Brightcove media API}
  s.test_files = [
    "test/helper.rb",
     "test/test_brightcove-api.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_runtime_dependency(%q<fakeweb>, ["= 1.2.8"])
    else
      s.add_dependency(%q<httparty>, ["= 0.5.2"])
      s.add_dependency(%q<fakeweb>, ["= 1.2.8"])
    end
  else
    s.add_dependency(%q<httparty>, ["= 0.5.2"])
    s.add_dependency(%q<fakeweb>, ["= 1.2.8"])
  end
end

